# Generated by Django 6.0.5 on 2026-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
